name: Clicky Download

on:
  workflow dispatch:
  schedule:
    -	cron: '0 0 * * 0'
    -	cron: '* * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install requests matplotlib
      - name: run clicky script
        run: |
            python clicky/runClickyScript.py
