name: "Clicky Download"
on: 
  schedule: 
    - 
      cron: "0 0 * * 0"
  workflow_dispatch: ~

jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - 
        name: "checkout branch"
        uses: actions/checkout@v2
      - 
        name: "Setup python"
        uses: actions/setup-python@v2
        with: 
          python-version: 3.8
      - 
        name: "Install dependencies"
        run: |
            python -m pip install --upgrade pip
            pip install requests matplotlib python-dotenv
      - 
        name: "Run clicky script"
        working-directory: "clicky"
        run: |
            python runClickyScript.py
      - 
        name: "Push changes"
        run: |-
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "Update Clicky Analytics"
            git push