name: Clicky Download

on:
  workflow dispatch:
  schedule:
    -	cron: '0 0 * * 0' # run each Sunday
    # Why does this also run on the first of each month? That may cause the graph to have innacurately scaled date intervals
    -	cron: '*/5 * * * *' # run every 5 minutes

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install requests matplotlib
      - name: run clicky script
        run: |
            python clicky/runClickyScript.py
