name: Deploy

on:
  workflow_run:
    workflows: ["Lint and Test"]
    branches: [main]
    types: 
      - completed

jobs:
  verify:
    name: Build and deploy
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "GitHub Action Bot"   

    - run: yarn install

    - run: yarn build

    - run: yarn deploy
