name: Update

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  update:
    name: Update CDC metadata files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.head_ref }}

    - name: Fetch files
      id: fetch
      run: |
        echo "::set-output name=cvx_status::$(curl -sSL -s -w '%{http_code}' -o src/components/HealthCardDisplay/iisstandards_cvx.xml https://www2a.cdc.gov/vaccines/iis/iisstandards/XML2.asp?rpt=cvx)"
        echo "::set-output name=tradename_status::$(curl -sSL -s -w '%{http_code}' -o src/components/HealthCardDisplay/iisstandards_tradename.xml https://www2a.cdc.gov/vaccines/iis/iisstandards/XML.asp?rpt=tradename)"

    - name: Check http status
      if: steps.fetch.outputs.cvx_status > 200 || steps.fetch.outputs.tradename_status > 200
      run: |
        echo "cvx_status ${{ steps.fetch.outputs.cvx_status }}, tradename_status ${{ steps.fetch.outputs.tradename_status }}"
        echo "::error title=Fetch::Failed to fetch CDC files"
        exit 1

    - name: Check dirty files
      id: check    
      run: |
        if git diff --exit-code; then
          echo "::set-output name=diff::false"
        else
          echo "::set-output name=diff::true"
        fi

    - name: Create Pull Request
      if: steps.check.outputs.diff == 'true'
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update CDC metadata files
        title: Update CDC metadata files
        body: Workflow auto-generated PR
        branch: update-cdc-metadata
        branch-suffix: timestamp
        reviewers: nkarip
