name: Update

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  update:
    name: Update CDC metadata files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}

    - name: Fetch files
      run: |
        curl -sSL -o src/components/HealthCardDisplay/iisstandards_cvx.xml https://www2a.cdc.gov/vaccines/iis/iisstandards/XML2.asp?rpt=cvx
        curl -sSL -o src/components/HealthCardDisplay/iisstandards_tradename.xml https://www2a.cdc.gov/vaccines/iis/iisstandards/XML.asp?rpt=tradename

    - name: Commit files
      run: |
        echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
        # Stage the files, commit and push
        git add src/components/HealthCardDisplay/
        git commit -m "update CDC files"
        git push github HEAD:${GITHUB_REF}
